import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Merriweather, Inter } from "next/font/google";

const merriweather = Merriweather({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-merriweather",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${merriweather.variable} ${inter.variable}`}
    >
      <body className="font-sans">
        <header className="p-4" />
        <main className="max-w-[800px] mx-auto px-4">{children}</main>
      </body>
    </html>
  );
}
